<?php

Route::get('/','ImportController@index')->name('index');
Route::post('crs','Import\ImportCrs')->name('crs');
Route::post('sigertan','Import\ImportSigertan')->name('sigertan');
Route::post('gadds','Import\ImportGadd')->name('gadds');
Route::post('absensi','Import\ImportAbsensi')->name('absensi');   
Route::post('users','Import\ImportUsers')->name('users');
Route::post('bidang','Import\ImportBidang')->name('bidang');
Route::post('vars','Import\ImportMagmaVar')->name('vars');
Route::post('dailies','Import\ImportVarHarian')->name('dailies');
Route::post('visuals','Import\ImportVarVisual')->name('visuals');
Route::post('klimatologi','Import\ImportVarKlimatologi')->name('klimatologi');
Route::post('gempa','Import\ImportGempa')->name('gempa');
Route::post('rekomendasi','Import\ImportVarRekomendasi')->name('rekomendasi');
Route::post('vens','Import\ImportMagmaVen')->name('vens');
Route::post('vona','Import\ImportVona')->name('vona');
Route::post('subscribers','Import\Importsubscriber')->name('subscribers');
Route::post('roq','Import\ImportRoq')->name('roq');
Route::get('status','ImportController@status')->name('status');